#!/usr/bin/env bash
# file to transfer from client to server

if [0 -pars 3 ]; then
echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
scp -i  -o StrictHostKeyChecking=no  @:~/
fi
