#!/usr/bin/env bash
# Installs and configures nginx, changes the listening port to 80
# and changes the nginx landing page.

sudo apt-get update
sudo apt-get install nginx -y
sudo ufw allow 22
sudo ufw allow 80
sudo ufw --force enable
sudo echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx restart
