#!/usr/bin/env bash
# Installs and configures nginx, changes the listening port to 80

sudo apt-get update
sudo apt-get upgrade
sudo apt-get install nginx -y
sudo ufw allow 80
sudo ufw --force enable
sudo systemctl status nginx
sudo echo "Hello World!" | sudo tee /var/www/html/index.html
sudo service nginx restart
