#!/usr/bin/env bash
# This is to redirect the the server to other page

sudo apt-get update
sudo apt-get install nginx -y
sudo ufw allow 22
sudo ufw allow 80
sudo ufw --force enable
sudo ufw status
systemctl status nginx 
sudo echo "Hello World!" | sudo tee -a /var/www/html/index.nginx-debian.html > /dev/null
sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.github.com/elayneh permanent;' /etc/nginx/sites-available/default
sudo service nginx restart

