#!/usr/bin/env bash
# This is to redirect the the server to other page

sudo apt-get update
sudo apt-get install nginx -y
sudo ufw allow 80
sudo ufw allow enable
sudo systemctl status nginx
sudo echo "Hello World!" | sudo tee /var/www/html/index.html
sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://youtu.be/MY5SatbZMAo permanent;' /etc/nginx/sites-available/default
sudo service nginx restart
