#!/usr/bin/env bash
# Install and configure two servers
apt-get update
apt-get -y install haproxy=1.6.\*
echo "ENABLED=1" >> /etc/default/haproxy
sed -i '/504.http/a \\nlisten http-in\n\tbind *:80\n\tmode http\n\tbalance roundrobin\n\tserver 1231-web-01 34.139.204.59:80 check\n\tserver 1231-web-02 3.235.148.75:80 check' /etc/haproxy/haproxy.cfg
sudo service haproxy start
