#!/usr/bin/env bash
# gives info about the ALX file

FILE="holbertonschool"
if [ -e $FILE ]
then
    echo "holbertonschool file exists"
    if [ -s $FILE ]
    then
	echo "school file is not empty"
    else
	echo "school file is empty"
    fi
    if [ -f $FILE ]
    then
	echo "school is a regular file"
    fi
else
    echo "school file does not exist"
fi
